version: '3.8'

services:
  app:
    build: .
    ports:
      - '8081:8081'
    volumes:
      - .:/home/app
    depends_on:
      - postgres
    restart: always
    environment:
      DATABASE_URL: postgres://app:app@localhost:5432/fans
      PORT: 8081
    command: bash -c "npm run start:dev"
    network_mode: host

  postgres:
    container_name: postgres
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: fans
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    network_mode: host

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://localhost/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    network_mode: host

volumes:
  postgres-data:
