version: '3.8'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/home/app
    depends_on:
      - postgres
    restart: always
    environment:
      DATABASE_URL: postgres://app:app@postgres:5432/fans
    command: bash -c "npm run start:dev"

  postgres:
    container_name: db
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: fans
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
